export const generateToken = () => {
    return {
        "muid": "14ae1b91-c7be-41ff-9e11-f60eaee432b8a9311c",
        "guid": "c9cce133-0ad6-46eb-ad8f-47ca93a4d235677e10",
        "sid": "e948d78f-7f64-441f-92a1-8a2a9fe06efc4bdeb3"
      };
};

export const localeListShippingCountries = () => {
    return {
        "countries": {
          "FR": "France",
          "PT": "Portugal",
          "SE": "Sweden",
          "US": "United States"
        },
        "html": "<option value=\"FR\">France</option><option value=\"PT\">Portugal</option><option value=\"SE\">Sweden</option><option value=\"US\">United States</option>"
      };
};

export const localeListSubdivisions = (countryCode) => {
    let data = {
        "FR": {
            "subdivisions": {
              "FR-01": "Ain",
              "FR-02": "Aisne",
              "FR-03": "Allier",
              "FR-06": "Alpes-Maritimes",
              "FR-04": "Alpes-de-Haute-Provence",
              "FR-08": "Ardennes",
              "FR-07": "Ardèche",
              "FR-09": "Ariège",
              "FR-10": "Aube",
              "FR-11": "Aude",
              "FR-ARA": "Auvergne-Rhône-Alpes",
              "FR-12": "Aveyron",
              "FR-67": "Bas-Rhin",
              "FR-13": "Bouches-du-Rhône",
              "FR-BFC": "Bourgogne-Franche-Comté",
              "FR-BRE": "Bretagne",
              "FR-14": "Calvados",
              "FR-15": "Cantal",
              "FR-CVL": "Centre-Val de Loire",
              "FR-16": "Charente",
              "FR-17": "Charente-Maritime",
              "FR-18": "Cher",
              "FR-CP": "Clipperton",
              "FR-19": "Corrèze",
              "FR-20R": "Corse",
              "FR-2A": "Corse-du-Sud",
              "FR-23": "Creuse",
              "FR-21": "Côte-d'Or",
              "FR-22": "Côtes-d'Armor",
              "FR-79": "Deux-Sèvres",
              "FR-24": "Dordogne",
              "FR-25": "Doubs",
              "FR-26": "Drôme",
              "FR-91": "Essonne",
              "FR-27": "Eure",
              "FR-28": "Eure-et-Loir",
              "FR-29": "Finistère",
              "FR-30": "Gard",
              "FR-32": "Gers",
              "FR-33": "Gironde",
              "FR-GES": "Grand-Est",
              "FR-971": "Guadeloupe",
              "FR-GP": "Guadeloupe",
              "FR-973": "Guyane (française)",
              "FR-GF": "Guyane (française)",
              "FR-68": "Haut-Rhin",
              "FR-2B": "Haute-Corse",
              "FR-31": "Haute-Garonne",
              "FR-43": "Haute-Loire",
              "FR-52": "Haute-Marne",
              "FR-74": "Haute-Savoie",
              "FR-70": "Haute-Saône",
              "FR-87": "Haute-Vienne",
              "FR-05": "Hautes-Alpes",
              "FR-65": "Hautes-Pyrénées",
              "FR-HDF": "Hauts-de-France",
              "FR-92": "Hauts-de-Seine",
              "FR-34": "Hérault",
              "FR-35": "Ille-et-Vilaine",
              "FR-36": "Indre",
              "FR-37": "Indre-et-Loire",
              "FR-38": "Isère",
              "FR-39": "Jura",
              "FR-RE": "La Réunion",
              "FR-974": "La Réunion",
              "FR-40": "Landes",
              "FR-41": "Loir-et-Cher",
              "FR-42": "Loire",
              "FR-44": "Loire-Atlantique",
              "FR-45": "Loiret",
              "FR-46": "Lot",
              "FR-47": "Lot-et-Garonne",
              "FR-48": "Lozère",
              "FR-49": "Maine-et-Loire",
              "FR-50": "Manche",
              "FR-51": "Marne",
              "FR-MQ": "Martinique",
              "FR-972": "Martinique",
              "FR-53": "Mayenne",
              "FR-976": "Mayotte",
              "FR-YT": "Mayotte",
              "FR-54": "Meurthe-et-Moselle",
              "FR-55": "Meuse",
              "FR-56": "Morbihan",
              "FR-57": "Moselle",
              "FR-58": "Nièvre",
              "FR-59": "Nord",
              "FR-NOR": "Normandie",
              "FR-NAQ": "Nouvelle-Aquitaine",
              "FR-NC": "Nouvelle-Calédonie",
              "FR-OCC": "Occitanie",
              "FR-60": "Oise",
              "FR-61": "Orne",
              "FR-75": "Paris",
              "FR-62": "Pas-de-Calais",
              "FR-PDL": "Pays-de-la-Loire",
              "FR-PF": "Polynésie française",
              "FR-PAC": "Provence-Alpes-Côte-d’Azur",
              "FR-63": "Puy-de-Dôme",
              "FR-64": "Pyrénées-Atlantiques",
              "FR-66": "Pyrénées-Orientales",
              "FR-69": "Rhône",
              "FR-BL": "Saint-Barthélemy",
              "FR-MF": "Saint-Martin",
              "FR-PM": "Saint-Pierre-et-Miquelon",
              "FR-72": "Sarthe",
              "FR-73": "Savoie",
              "FR-71": "Saône-et-Loire",
              "FR-76": "Seine-Maritime",
              "FR-93": "Seine-Saint-Denis",
              "FR-77": "Seine-et-Marne",
              "FR-80": "Somme",
              "FR-81": "Tarn",
              "FR-82": "Tarn-et-Garonne",
              "FR-TF": "Terres australes françaises",
              "FR-90": "Territoire de Belfort",
              "FR-95": "Val-d'Oise",
              "FR-94": "Val-de-Marne",
              "FR-83": "Var",
              "FR-84": "Vaucluse",
              "FR-85": "Vendée",
              "FR-86": "Vienne",
              "FR-88": "Vosges",
              "FR-WF": "Wallis-et-Futuna",
              "FR-89": "Yonne",
              "FR-78": "Yvelines",
              "FR-IDF": "Île-de-France"
            },
            "html": "<option value=\"FR-01\">Ain</option><option value=\"FR-02\">Aisne</option><option value=\"FR-03\">Allier</option><option value=\"FR-06\">Alpes-Maritimes</option><option value=\"FR-04\">Alpes-de-Haute-Provence</option><option value=\"FR-08\">Ardennes</option><option value=\"FR-07\">Ardèche</option><option value=\"FR-09\">Ariège</option><option value=\"FR-10\">Aube</option><option value=\"FR-11\">Aude</option><option value=\"FR-ARA\">Auvergne-Rhône-Alpes</option><option value=\"FR-12\">Aveyron</option><option value=\"FR-67\">Bas-Rhin</option><option value=\"FR-13\">Bouches-du-Rhône</option><option value=\"FR-BFC\">Bourgogne-Franche-Comté</option><option value=\"FR-BRE\">Bretagne</option><option value=\"FR-14\">Calvados</option><option value=\"FR-15\">Cantal</option><option value=\"FR-CVL\">Centre-Val de Loire</option><option value=\"FR-16\">Charente</option><option value=\"FR-17\">Charente-Maritime</option><option value=\"FR-18\">Cher</option><option value=\"FR-CP\">Clipperton</option><option value=\"FR-19\">Corrèze</option><option value=\"FR-20R\">Corse</option><option value=\"FR-2A\">Corse-du-Sud</option><option value=\"FR-23\">Creuse</option><option value=\"FR-21\">Côte-d'Or</option><option value=\"FR-22\">Côtes-d'Armor</option><option value=\"FR-79\">Deux-Sèvres</option><option value=\"FR-24\">Dordogne</option><option value=\"FR-25\">Doubs</option><option value=\"FR-26\">Drôme</option><option value=\"FR-91\">Essonne</option><option value=\"FR-27\">Eure</option><option value=\"FR-28\">Eure-et-Loir</option><option value=\"FR-29\">Finistère</option><option value=\"FR-30\">Gard</option><option value=\"FR-32\">Gers</option><option value=\"FR-33\">Gironde</option><option value=\"FR-GES\">Grand-Est</option><option value=\"FR-971\">Guadeloupe</option><option value=\"FR-GP\">Guadeloupe</option><option value=\"FR-973\">Guyane (française)</option><option value=\"FR-GF\">Guyane (française)</option><option value=\"FR-68\">Haut-Rhin</option><option value=\"FR-2B\">Haute-Corse</option><option value=\"FR-31\">Haute-Garonne</option><option value=\"FR-43\">Haute-Loire</option><option value=\"FR-52\">Haute-Marne</option><option value=\"FR-74\">Haute-Savoie</option><option value=\"FR-70\">Haute-Saône</option><option value=\"FR-87\">Haute-Vienne</option><option value=\"FR-05\">Hautes-Alpes</option><option value=\"FR-65\">Hautes-Pyrénées</option><option value=\"FR-HDF\">Hauts-de-France</option><option value=\"FR-92\">Hauts-de-Seine</option><option value=\"FR-34\">Hérault</option><option value=\"FR-35\">Ille-et-Vilaine</option><option value=\"FR-36\">Indre</option><option value=\"FR-37\">Indre-et-Loire</option><option value=\"FR-38\">Isère</option><option value=\"FR-39\">Jura</option><option value=\"FR-RE\">La Réunion</option><option value=\"FR-974\">La Réunion</option><option value=\"FR-40\">Landes</option><option value=\"FR-41\">Loir-et-Cher</option><option value=\"FR-42\">Loire</option><option value=\"FR-44\">Loire-Atlantique</option><option value=\"FR-45\">Loiret</option><option value=\"FR-46\">Lot</option><option value=\"FR-47\">Lot-et-Garonne</option><option value=\"FR-48\">Lozère</option><option value=\"FR-49\">Maine-et-Loire</option><option value=\"FR-50\">Manche</option><option value=\"FR-51\">Marne</option><option value=\"FR-MQ\">Martinique</option><option value=\"FR-972\">Martinique</option><option value=\"FR-53\">Mayenne</option><option value=\"FR-976\">Mayotte</option><option value=\"FR-YT\">Mayotte</option><option value=\"FR-54\">Meurthe-et-Moselle</option><option value=\"FR-55\">Meuse</option><option value=\"FR-56\">Morbihan</option><option value=\"FR-57\">Moselle</option><option value=\"FR-58\">Nièvre</option><option value=\"FR-59\">Nord</option><option value=\"FR-NOR\">Normandie</option><option value=\"FR-NAQ\">Nouvelle-Aquitaine</option><option value=\"FR-NC\">Nouvelle-Calédonie</option><option value=\"FR-OCC\">Occitanie</option><option value=\"FR-60\">Oise</option><option value=\"FR-61\">Orne</option><option value=\"FR-75\">Paris</option><option value=\"FR-62\">Pas-de-Calais</option><option value=\"FR-PDL\">Pays-de-la-Loire</option><option value=\"FR-PF\">Polynésie française</option><option value=\"FR-PAC\">Provence-Alpes-Côte-d’Azur</option><option value=\"FR-63\">Puy-de-Dôme</option><option value=\"FR-64\">Pyrénées-Atlantiques</option><option value=\"FR-66\">Pyrénées-Orientales</option><option value=\"FR-69\">Rhône</option><option value=\"FR-BL\">Saint-Barthélemy</option><option value=\"FR-MF\">Saint-Martin</option><option value=\"FR-PM\">Saint-Pierre-et-Miquelon</option><option value=\"FR-72\">Sarthe</option><option value=\"FR-73\">Savoie</option><option value=\"FR-71\">Saône-et-Loire</option><option value=\"FR-76\">Seine-Maritime</option><option value=\"FR-93\">Seine-Saint-Denis</option><option value=\"FR-77\">Seine-et-Marne</option><option value=\"FR-80\">Somme</option><option value=\"FR-81\">Tarn</option><option value=\"FR-82\">Tarn-et-Garonne</option><option value=\"FR-TF\">Terres australes françaises</option><option value=\"FR-90\">Territoire de Belfort</option><option value=\"FR-95\">Val-d'Oise</option><option value=\"FR-94\">Val-de-Marne</option><option value=\"FR-83\">Var</option><option value=\"FR-84\">Vaucluse</option><option value=\"FR-85\">Vendée</option><option value=\"FR-86\">Vienne</option><option value=\"FR-88\">Vosges</option><option value=\"FR-WF\">Wallis-et-Futuna</option><option value=\"FR-89\">Yonne</option><option value=\"FR-78\">Yvelines</option><option value=\"FR-IDF\">Île-de-France</option>"
          },
          "PT": {
            "subdivisions": {
                "PT-01": "Aveiro",
                "PT-02": "Beja",
                "PT-03": "Braga",
                "PT-04": "Bragança",
                "PT-05": "Castelo Branco",
                "PT-06": "Coimbra",
                "PT-08": "Faro",
                "PT-09": "Guarda",
                "PT-10": "Leiria",
                "PT-11": "Lisboa",
                "PT-12": "Portalegre",
                "PT-13": "Porto",
                "PT-30": "Região Autónoma da Madeira",
                "PT-20": "Região Autónoma dos Açores",
                "PT-14": "Santarém",
                "PT-15": "Setúbal",
                "PT-16": "Viana do Castelo",
                "PT-17": "Vila Real",
                "PT-18": "Viseu",
                "PT-07": "Évora"
            },
            "html": "<option value=\"PT-01\">Aveiro</option><option value=\"PT-02\">Beja</option><option value=\"PT-03\">Braga</option><option value=\"PT-04\">Bragança</option><option value=\"PT-05\">Castelo Branco</option><option value=\"PT-06\">Coimbra</option><option value=\"PT-08\">Faro</option><option value=\"PT-09\">Guarda</option><option value=\"PT-10\">Leiria</option><option value=\"PT-11\">Lisboa</option><option value=\"PT-12\">Portalegre</option><option value=\"PT-13\">Porto</option><option value=\"PT-30\">Região Autónoma da Madeira</option><option value=\"PT-20\">Região Autónoma dos Açores</option><option value=\"PT-14\">Santarém</option><option value=\"PT-15\">Setúbal</option><option value=\"PT-16\">Viana do Castelo</option><option value=\"PT-17\">Vila Real</option><option value=\"PT-18\">Viseu</option><option value=\"PT-07\">Évora</option>"
          },
          "SE": {
            "subdivisions": {
                "SE-K": "Blekinge län [SE-10]",
                "SE-W": "Dalarnas län [SE-20]",
                "SE-I": "Gotlands län [SE-09]",
                "SE-X": "Gävleborgs län [SE-21]",
                "SE-N": "Hallands län [SE-13]",
                "SE-Z": "Jämtlands län [SE-23]",
                "SE-F": "Jönköpings län [SE-06]",
                "SE-H": "Kalmar län [SE-08]",
                "SE-G": "Kronobergs län [SE-07]",
                "SE-BD": "Norrbottens län [SE-25]",
                "SE-M": "Skåne län [SE-12]",
                "SE-AB": "Stockholms län [SE-01]",
                "SE-D": "Södermanlands län [SE-04]",
                "SE-C": "Uppsala län [SE-03]",
                "SE-S": "Värmlands län [SE-17]",
                "SE-AC": "Västerbottens län [SE-24]",
                "SE-Y": "Västernorrlands län [SE-22]",
                "SE-U": "Västmanlands län [SE-19]",
                "SE-O": "Västra Götalands län [SE-14]",
                "SE-T": "Örebro län [SE-18]",
                "SE-E": "Östergötlands län [SE-05]"
            },
            "html": "<option value=\"SE-K\">Blekinge län [SE-10]</option><option value=\"SE-W\">Dalarnas län [SE-20]</option><option value=\"SE-I\">Gotlands län [SE-09]</option><option value=\"SE-X\">Gävleborgs län [SE-21]</option><option value=\"SE-N\">Hallands län [SE-13]</option><option value=\"SE-Z\">Jämtlands län [SE-23]</option><option value=\"SE-F\">Jönköpings län [SE-06]</option><option value=\"SE-H\">Kalmar län [SE-08]</option><option value=\"SE-G\">Kronobergs län [SE-07]</option><option value=\"SE-BD\">Norrbottens län [SE-25]</option><option value=\"SE-M\">Skåne län [SE-12]</option><option value=\"SE-AB\">Stockholms län [SE-01]</option><option value=\"SE-D\">Södermanlands län [SE-04]</option><option value=\"SE-C\">Uppsala län [SE-03]</option><option value=\"SE-S\">Värmlands län [SE-17]</option><option value=\"SE-AC\">Västerbottens län [SE-24]</option><option value=\"SE-Y\">Västernorrlands län [SE-22]</option><option value=\"SE-U\">Västmanlands län [SE-19]</option><option value=\"SE-O\">Västra Götalands län [SE-14]</option><option value=\"SE-T\">Örebro län [SE-18]</option><option value=\"SE-E\">Östergötlands län [SE-05]</option>"
          },
          "US": {
            "subdivisions": {
                "US-AL": "Alabama",
                "US-AK": "Alaska",
                "US-AS": "American Samoa",
                "US-AZ": "Arizona",
                "US-AR": "Arkansas",
                "US-CA": "California",
                "US-CO": "Colorado",
                "US-CT": "Connecticut",
                "US-DE": "Delaware",
                "US-DC": "District of Columbia",
                "US-FL": "Florida",
                "US-GA": "Georgia",
                "US-GU": "Guam",
                "US-HI": "Hawaii",
                "US-ID": "Idaho",
                "US-IL": "Illinois",
                "US-IN": "Indiana",
                "US-IA": "Iowa",
                "US-KS": "Kansas",
                "US-KY": "Kentucky",
                "US-LA": "Louisiana",
                "US-ME": "Maine",
                "US-MD": "Maryland",
                "US-MA": "Massachusetts",
                "US-MI": "Michigan",
                "US-MN": "Minnesota",
                "US-MS": "Mississippi",
                "US-MO": "Missouri",
                "US-MT": "Montana",
                "US-NE": "Nebraska",
                "US-NV": "Nevada",
                "US-NH": "New Hampshire",
                "US-NJ": "New Jersey",
                "US-NM": "New Mexico",
                "US-NY": "New York",
                "US-NC": "North Carolina",
                "US-ND": "North Dakota",
                "US-MP": "Northern Mariana Islands",
                "US-OH": "Ohio",
                "US-OK": "Oklahoma",
                "US-OR": "Oregon",
                "US-PA": "Pennsylvania",
                "US-PR": "Puerto Rico",
                "US-RI": "Rhode Island",
                "US-SC": "South Carolina",
                "US-SD": "South Dakota",
                "US-TN": "Tennessee",
                "US-TX": "Texas",
                "US-UM": "United States Minor Outlying Islands",
                "US-UT": "Utah",
                "US-VT": "Vermont",
                "US-VI": "Virgin Islands, U.S.",
                "US-VA": "Virginia",
                "US-WA": "Washington",
                "US-WV": "West Virginia",
                "US-WI": "Wisconsin",
                "US-WY": "Wyoming"
            },
            "html": "<option value=\"US-AL\">Alabama</option><option value=\"US-AK\">Alaska</option><option value=\"US-AS\">American Samoa</option><option value=\"US-AZ\">Arizona</option><option value=\"US-AR\">Arkansas</option><option value=\"US-CA\">California</option><option value=\"US-CO\">Colorado</option><option value=\"US-CT\">Connecticut</option><option value=\"US-DE\">Delaware</option><option value=\"US-DC\">District of Columbia</option><option value=\"US-FL\">Florida</option><option value=\"US-GA\">Georgia</option><option value=\"US-GU\">Guam</option><option value=\"US-HI\">Hawaii</option><option value=\"US-ID\">Idaho</option><option value=\"US-IL\">Illinois</option><option value=\"US-IN\">Indiana</option><option value=\"US-IA\">Iowa</option><option value=\"US-KS\">Kansas</option><option value=\"US-KY\">Kentucky</option><option value=\"US-LA\">Louisiana</option><option value=\"US-ME\">Maine</option><option value=\"US-MD\">Maryland</option><option value=\"US-MA\">Massachusetts</option><option value=\"US-MI\">Michigan</option><option value=\"US-MN\">Minnesota</option><option value=\"US-MS\">Mississippi</option><option value=\"US-MO\">Missouri</option><option value=\"US-MT\">Montana</option><option value=\"US-NE\">Nebraska</option><option value=\"US-NV\">Nevada</option><option value=\"US-NH\">New Hampshire</option><option value=\"US-NJ\">New Jersey</option><option value=\"US-NM\">New Mexico</option><option value=\"US-NY\">New York</option><option value=\"US-NC\">North Carolina</option><option value=\"US-ND\">North Dakota</option><option value=\"US-MP\">Northern Mariana Islands</option><option value=\"US-OH\">Ohio</option><option value=\"US-OK\">Oklahoma</option><option value=\"US-OR\">Oregon</option><option value=\"US-PA\">Pennsylvania</option><option value=\"US-PR\">Puerto Rico</option><option value=\"US-RI\">Rhode Island</option><option value=\"US-SC\">South Carolina</option><option value=\"US-SD\">South Dakota</option><option value=\"US-TN\">Tennessee</option><option value=\"US-TX\">Texas</option><option value=\"US-UM\">United States Minor Outlying Islands</option><option value=\"US-UT\">Utah</option><option value=\"US-VT\">Vermont</option><option value=\"US-VI\">Virgin Islands, U.S.</option><option value=\"US-VA\">Virginia</option><option value=\"US-WA\">Washington</option><option value=\"US-WV\">West Virginia</option><option value=\"US-WI\">Wisconsin</option><option value=\"US-WY\">Wyoming</option>"
          }
    };
    return data[countryCode];
}

export const getShippingOptions = (tokenId, {country, region}) => {
    return [
        {
          "id": "ship_Kvg9l6Ozpw1bB7",
          "description": "International",
          "price": {
            "raw": 10,
            "formatted": "10.00",
            "formatted_with_symbol": "$10.00",
            "formatted_with_code": "10.00 USD"
          },
          "countries": [
            "FR",
            "PT",
            "SE"
          ]
        }
      ];
};